src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientRepository::class)
 */
class Patient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="string", length=20)
     */
    private $numero_fiche;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $genre;


    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lieu_naissance;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $createdBy;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_abonne;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $postnom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $adresse;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroFiche(): ?string
    {
        return $this->numero_fiche;
    }

    public function setNumeroFiche(string $numero_fiche): self
    {
        $this->numero_fiche = $numero_fiche;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getIsAbonne(): ?bool
    {
        return $this->is_abonne;
    }

    public function setIsAbonne(bool $is_abonne): self
    {
        $this->is_abonne = $is_abonne;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPostnom(): ?string
    {
        return $this->postnom;
    }

    public function setPostnom(string $postnom): self
    {
        $this->postnom = $postnom;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


}

src/Entity/SignesVitaux.php
<?php

namespace App\Entity;

use App\Repository\SignesVitauxRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SignesVitauxRepository::class)
 */
class SignesVitaux
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;





    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;



    /**
     * @ORM\Column(type="boolean")
     */
    private $active;



    /**
     * @ORM\ManyToMany(targetEntity=User::class)
     */
    private $created;



    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $patient;



    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tension_arterielle;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $poids;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $temperature;

    /**
     * @ORM\ManyToOne(targetEntity=Cabinet::class)
     */
    private $cabinet;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;








    public function getId(): ?int
    {
        return $this->id;
    }






    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): ?self
    {
        $this->created_at = $created_at;

        return $this;
    }




    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): ?self
    {
        $this->active = $active;

        return $this;
    }



    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): ?self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }



    public function getTensionArterielle(): ?float
    {
        return $this->tension_arterielle;
    }

    public function setTensionArterielle(?float $tension_arterielle): self
    {
        $this->tension_arterielle = $tension_arterielle;

        return $this;
    }

    public function getPoids(): ?float
    {
        return $this->poids;
    }

    public function setPoids(?float $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getTemperature(): ?float
    {
        return $this->temperature;
    }

    public function setTemperature(?float $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getCabinet(): ?Cabinet
    {
        return $this->cabinet;
    }

    public function setCabinet(?Cabinet $cabinet): self
    {
        $this->cabinet = $cabinet;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }





}

src/Form/SignesVitauxType.php
<?php

namespace App\Form;

use App\Entity\Cabinet;
use App\Entity\Service;
use App\Entity\SignesVitaux;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

class SignesVitauxType extends AbstractType
{
    private $user;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->user = $tokenStorage->getToken()->getUser();
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tension_arterielle')
            ->add('poids')
            ->add('temperature')
            ->add('created_at', HiddenType::class)
            ->add('active', HiddenType::class, [
                'data'=>true
            ])
            ->add('cabinet', EntityType::class, [
                'class'=>Cabinet::class,
                'choice_label'=>'designation'
            ])
            ->add('created_by', HiddenType::class, [

            ])
            ->add('save', SubmitType::class, ['label'=>'Enregistrer', 'attr'=>['class'=>'btn btn-primary mt-3']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SignesVitaux::class,

        ]);
    }
}

src/Controller/SignesVitauxController.php
<?php

namespace App\Controller;

use App\Entity\Acte;
use App\Entity\PaiementActe;
use App\Entity\Patient;
use App\Entity\SignesVitaux;
use App\Form\SignesVitauxType;
use App\Repository\PatientRepository;
use App\Repository\SignesVitauxRepository;
use Cassandra\Date;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\This;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SignesVitauxController extends AbstractController
{
    /**
     * @Route("/signes/vitaux", name="signes_vitaux")
     */
    public function index(): Response
    {
        $patient = new Patient();
        $patients = $this->getDoctrine()->getRepository(SignesVitaux::class)
            ->findBy([
                'active' => true,
                'cabinet'=>null

            ],
                [
                'created_at' => 'DESC',

            ]);
        return $this->render('signes_vitaux/index.html.twig', [
            'controller_name' => 'SignesVitauxController',
            'patients' => $patients,
        ]);
    }

    /**
     * @Route("/prelever/{id}/{p?}", name="prelever")
     */
    public function prelever_signes_vitaux(int $id, ?int $p, PatientRepository $patientRepository, Request $request,
                                           EntityManagerInterface $entityManager, SignesVitauxRepository $signesVitauxRepository)
    {
        $signes = new SignesVitaux();
        $vitaux = $this->getDoctrine()->getRepository(SignesVitaux::class)
            ->findByPatient($id);
        $form = $this->createForm(SignesVitauxType::class);
        $form->handleRequest($request);

        $patient = $patientRepository->find($id);
        $actual = new \DateTime();
        $age = date_diff($actual, $patient->getDateNaissance());
        if($form->isSubmitted() && $form->isValid()) {
            //$form['created_at']->setData(new \DateTime('now'));
            //$signes_vitaux = $form->getData();
            //$signes_vitaux->setCreatedAt(new \DateTime('now'));
            //$signes_vitaux->setCreatedBy($this->getUser());
            //$signes_vitaux->setPatient($patientRepository->find($id));
            $signesvitaux = $signesVitauxRepository->find($p);

            if (!$signesvitaux) {
                throw $this->createNotFoundException(
                    "Aucun enregistrement de ce patient retrouvé".$p
                );
            }
            $signesvitaux->setPoids($form['poids']->getData());
            $signesvitaux->setTemperature($form['temperature']->getData());
            $signesvitaux->setTensionArterielle($form['tension_arterielle']->getData());
            $signesvitaux->setCabinet($form['cabinet']->getData());
            //$signesvitaux->setService($form['service']->getData());
            $signesvitaux->setUpdatedAt(new \DateTime('now'));
            $signesvitaux->setCreatedBy($this->getUser());
            $signesvitaux->setPatient($patient);
            $entityManager->persist($signesvitaux);
            $entityManager->flush();
            //return $this->redirectToRoute('patient');
            return $this->render('signes_vitaux/new_signes_vitaux.html.twig', [
                'patient'=>$patient,
                'signes'=>$vitaux,
                'age'=>$age->y
            ]);
        }
        if(!is_null($p)){
            $signesvitaux = $signesVitauxRepository->find($p);
            if (!$signesvitaux) {
                throw $this->$this->createNotFoundException(
                    "Aucun enregistrement retrouvé"
                );
            }
            $patient = $patientRepository->find($id);
            $actual = new \DateTime();
            $age = date_diff($actual, $patient->getDateNaissance());
            return $this->render('signes_vitaux/new_signes_vitaux.html.twig',[
                'patient'=> $patient,
                'form'=> $form->createView(),
                'prelever'=>$p,
                'age'=>$age->y
            ]);
        }
        $patient = $patientRepository->find($id);
        $actual = new \DateTime();
        $age = date_diff($actual, $patient->getDateNaissance());
        return $this->render('signes_vitaux/new_signes_vitaux.html.twig',[
            'patient'=> $patient,
            'form'=> $form->createView(),
            'signes'=>$vitaux,
            'age'=>$age->y
        ]);
    }

    /**
     * @Route("/nouveaux/{id}", name="nouveaux_signes", defaults={"tension_arterielle": ""})
     */
    public function nouveaux_signes( int $id, PatientRepository $patientRepository, EntityManagerInterface $entityManager)
    {
        $signes = new SignesVitaux();
        $signes->setPatient($patientRepository->find($id));
        $signes->setActive(true);
        $signes->setCreatedBy($this->getUser());
        $signes->setCreatedAt(new \DateTime('now'));
        $entityManager->persist($signes);
        // paiement fiche
        $fiche = $this->getDoctrine()->getRepository(Acte::class)
            ->findActeFiche();

        $paiement = new PaiementActe();
        $paiement->setActe($fiche);
        $paiement->setUser($this->getUser());
        $paiement->setActive(true);
        $paiement->setPatient($patientRepository->find($id));
        $paiement->setDatePaiement(new \DateTime('now'));
        $entityManager->persist($paiement);

        $entityManager->flush();
        $patient = $patientRepository->find($id);
        $signes = new SignesVitaux();
        $vitaux = $this->getDoctrine()->getRepository(SignesVitaux::class)
            ->findBy([
                'active'=>true,
                'patient'=>$patient
            ],[
                'created_at'=>'DESC'
            ]);
        $actual = new \DateTime();
        $age = date_diff($actual, $patient->getDateNaissance());
        return $this->render('signes_vitaux/new_signes_vitaux.html.twig',[
            'patient'=> $patient,
            'signes'=>$vitaux,
            'age'=>$age->y
        ]);
    }


}

templates/signes_vitaux/index.html.twig
{% include "_extension/sidebar.html.twig" %}

{% block title %}Hello PatientController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        {% for message in app.flashes('notice') %}
            <button type="button" class="btn btn-success toastsDefaultSuccess">
                {{ message }}
            </button>

        {% endfor %}
        <h1>Nouveaux patients </h1>

        {# {{ dump(patients) }} #}
        <table class="table table-hover">
            <thead class="bg-primary">
            <th>#</th>
            <th>Fiche</th>
            <th>Nom</th>
            <th>Postnom</th>
            <th>Genre</th>
            <th>Date Naissance</th>
            <th>Actions</th>
            <!--th>Action</th-->
            </thead>
            <tbody>
            {% with { i : 1 } %}
                {% for patient in patients %}

                    <tr>
                        <td>{{ i }}</td>
                        <td>{{ patient.patient.numeroFiche|upper }}</td>
                        <td>{{ patient.patient.nom }}</td>
                        <td>{{ patient.patient.postnom }}</td>
                        <td>{{ patient.patient.genre }}</td>
                        <td>{{ patient.patient.dateNaissance|date('d-m-Y') }}</td>
                        {#
                        <td>{% if is_granted('ROLE_USER') %}
                                <a href="{{ path('new_paiement_acte',{ 'id': patient.id}) }}">Payer fiche</a>
                            {% else %}
                                <a href="{{ path('new_paiement_acte',{ 'id': patient.id}) }}">Non Authorisé</a>
                            {% endif %}
                        </td> #}
                        <td>
                            <a href="{{ path('prelever',{ id: patient.patient.id, p:patient.id }) }}">Prelever</a>
                        </td>
                    </tr>
                    {% set i = i+1 %}
                {% endfor %}

            {% endwith %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/signes_vitaux/new_signes_vitaux.html.twig
{% include "_extension/sidebar.html.twig" %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Patient à prelever</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">User Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">

                    <!-- Profile Image -->
                        <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle"
                                     src="../../dist/img/user4-128x128.jpg"
                                     alt="User profile picture">
                            </div>

                            <h3 class="profile-username text-center">{{ patient.nom|upper ~' '~ patient.postnom|upper }}</h3>

                            <p class="text-muted text-center">Age :  {{ age }} ans</p>

                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b>Fiche</b> <a class="float-right">{{ patient.numeroFiche|upper }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Genre</b> <a class="float-right">{{ patient.genre }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Date de n.</b> <a class="float-right">{{ patient.dateNaissance | date("d-m-Y") }}</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    {% if signes is defined %}
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Prelevements precedents</h3>
                            </div>
                            <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                    <thead>
                                    <tr>
                                        <th style="width: 10px">N°</th>
                                        <th>Date Consultation</th>
                                        <th>T°</th>
                                        <th>Tension Arterielle</th>
                                        <th>Poids</th>
                                        <th>Cabinet Traitant</th>
                                        <th>Observation</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% with { i : 1 } %}
                                        {% for signe in signes %}
                                            <tr>
                                                <td>{{ i }}</td>
                                                <td>{{ signe.createdAt|date('d-m-Y') }}</td>
                                                <td>{{ signe.poids }}</td>
                                                <td>{{ signe.temperature }}</td>
                                                <td>{{ signe.tensionArterielle }}</td>
                                                <td>{{ signe.cabinet.designation is defined?signe.cabinet.designation:'-' }}</td>
                                                <td>
                                                    {% if(signe.cabinet.designation is defined) %}
                                                        <span>ok</span>
                                                    {% else %}
                                                        <a href="{{ path('prelever', {'id': signe.patient.id, 'p': signe.id}) }}">Prelever</a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                            {% set i = i+1 %}
                                        {% endfor %}
                                    {% endwith %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                                <!-- /.post -->

                                {% elseif prelever is defined %}
                                <div class="card">
                                    <div class="card-header p-2">
                                        <h3 class="card-title">Faire un prelevement</h3>
                                    </div><!-- /.card-header -->
                                    <div class="card-body">
                                        {{ form_start(form) }}
                                        {{ form_errors(form) }}
                                        {{ form_row(form.poids, {'attr':{'class':'form-control'}}) }}
                                        {{ form_row(form.temperature, {'attr':{'class':'form-control'}}) }}
                                        {{ form_row(form.tension_arterielle, {'attr':{'class':'form-control'}}) }}
                                        {{ form_row(form.cabinet, {'attr':{'class':'form-control'}}) }}
                                        {{ form_end(form) }}
                                    </div>
                                </div>
                    {% else %}
                        {{ "rien" }}
                    {% endif %}
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% block javascripts %}
    <script src="{{ asset('my_js/speech_to_text.js') }}"></script>
{% endblock %}

{% include "/_extension/footer.html.twig" %}